"""Tests for render.py format conventions.

Non-negotiable: the empty-state report must be fully-formed (header, four-stat
band, dominant table with placeholder, footer) — em-dashes for not-yet-present
values, explicit zeros where zero is real.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest

import render
from render import (
    EMDASH,
    Stat,
    TableSpec,
    format_count,
    format_currency,
    format_human_time,
    format_iso_ts,
    format_pct,
    format_ratio,
    format_sparkline,
    format_trade_id,
    format_variant_name,
    render_flags_section,
    render_four_stat_band,
    render_index,
    render_marginalia_footer,
    render_v1_report,
)


def test_format_currency_zero_is_real() -> None:
    assert format_currency(0.0) == "$0.00"
    assert format_currency(0) == "$0.00"


def test_format_currency_emdash_for_none() -> None:
    assert format_currency(None) == EMDASH


def test_format_currency_negative_and_positive() -> None:
    assert format_currency(-38.20) == "-$38.20"
    assert format_currency(112.40) == "$112.40"
    assert format_currency(1247.34) == "$1,247.34"


def test_format_pct_signs() -> None:
    assert format_pct(0.0) == "0.00%"
    assert format_pct(5.23) == "+5.23%"
    assert format_pct(-3.8) == "-3.80%"
    assert format_pct(None) == EMDASH


def test_format_count_zero_is_real() -> None:
    assert format_count(0) == "0"
    assert format_count(347) == "347"
    assert format_count(None) == EMDASH


def test_format_ratio() -> None:
    assert format_ratio(1.34) == "1.34"
    assert format_ratio(-0.21) == "-0.21"
    assert format_ratio(None) == EMDASH


def test_format_iso_ts() -> None:
    dt = datetime(2026, 5, 2, 16, 6, 29, tzinfo=timezone.utc)
    assert format_iso_ts(dt) == "2026-05-02T16:06:29Z"
    assert format_iso_ts(None) == EMDASH


def test_format_human_time() -> None:
    dt = datetime(2026, 5, 2, 16, 6, tzinfo=timezone.utc)
    assert format_human_time(dt) == "May 02, 16:06 UTC"
    assert format_human_time(None) == EMDASH


def test_format_variant_name() -> None:
    assert format_variant_name("bollinger_default") == "`bollinger_default`"
    assert format_variant_name(None) == EMDASH
    assert format_variant_name("") == EMDASH


def test_format_trade_id() -> None:
    assert (
        format_trade_id(142)
        == "[`#0142`](https://app.alpaca.markets/paper/orders/142)"
    )
    assert format_trade_id(None) == EMDASH
    assert format_trade_id(None, proposed=True) == "[#proposed]"
    assert format_trade_id("abc-123") == "[`#abc-123`](https://app.alpaca.markets/paper/orders/abc-123)"


def test_format_sparkline_basic() -> None:
    line = format_sparkline([1.0, 2.0, 3.0, 4.0])
    assert len(line) == 4
    assert all(c in "▁▂▃▄▅▆▇█" for c in line)
    assert line[0] == "▁"
    assert line[-1] == "█"


def test_format_sparkline_empty() -> None:
    assert format_sparkline([]) == EMDASH
    assert format_sparkline(None) == EMDASH


def test_format_sparkline_flat() -> None:
    line = format_sparkline([5.0, 5.0, 5.0])
    assert len(line) == 3
    assert len(set(line)) == 1


def test_four_stat_band_requires_exactly_four() -> None:
    with pytest.raises(ValueError, match="exactly 4"):
        render_four_stat_band([Stat("A", "1")])
    with pytest.raises(ValueError, match="exactly 4"):
        render_four_stat_band([Stat(f"L{i}", str(i)) for i in range(5)])


def test_four_stat_band_shape() -> None:
    stats = [
        Stat("Variants registered", EMDASH, "0 enabled"),
        Stat("Trades in period", "0", "paper"),
        Stat("P&L", "$0.00", EMDASH + "%"),
        Stat("System uptime", "100%", "last 4w"),
    ]
    out = render_four_stat_band(stats)
    lines = out.split("\n")
    assert len(lines) == 4
    assert lines[0] == "| Variants registered | Trades in period | P&L | System uptime |"
    assert lines[1] == "| :--- | :--- | :--- | :--- |"
    assert "**—**" in lines[2]
    assert "**0**" in lines[2]
    assert "**$0.00**" in lines[2]
    assert "0 enabled" in lines[3]
    assert "paper" in lines[3]


def test_flags_section_empty_is_collapsed() -> None:
    out = render_flags_section([])
    assert out == "§ Flags · none"


def test_flags_section_populated_uses_signal_red() -> None:
    out = render_flags_section(["Run failed at 14:00", "Drawdown breached"])
    assert "🔴 § Flags · 2 active" in out
    assert "▸ Run failed at 14:00" in out
    assert "▸ Drawdown breached" in out


def test_marginalia_footer() -> None:
    out = render_marginalia_footer(generator="replay.py v0.1.0")
    assert out.startswith("---")
    assert "paper-api.alpaca.markets/v2/orders" in out
    assert "generated by replay.py v0.1.0" in out
    assert "github.com/pwysocan-droid/algotrading-paper" in out


def _empty_state_replay_data() -> dict:
    return {
        "title": "algotrading-paper / replay",
        "subtitle": "Variant — null  ·  Period — 2026-04-02 → 2026-05-02 (30d)",
        "timestamp": datetime(2026, 5, 2, 16, 6, 29, tzinfo=timezone.utc),
        "count_summary": "0 trades",
        "links": [
            ("run log →", "runs/2026-05-02T160629.log"),
            ("↗ index", "INDEX.md"),
        ],
        "stats": [
            Stat("Variants registered", EMDASH, "0 enabled"),
            Stat("Trades in period", "0", "paper"),
            Stat("P&L", "$0.00", EMDASH + "%"),
            Stat("System uptime", "100%", "last 4w"),
        ],
        "flags": [],
        "dominant_table": TableSpec(
            section_marker="§ 01 — Per-variant performance · last 30 days",
            columns=["Variant", "n", "30d sparkline", "P&L", "Pct", "Sharpe", "Max DD", "Status"],
            rows=[],
            empty_row_message="no variants registered",
        ),
        "sub_tables": [
            TableSpec(
                section_marker="§ 02 — Bars in period · by symbol",
                columns=["Symbol", "Bars", "First", "Last", "Gaps"],
                rows=[],
                empty_row_message="no bars yet",
            ),
            TableSpec(
                section_marker="§ 03 — Run summary",
                columns=["Phase", "Status", "Duration", "Notes"],
                rows=[
                    ["fetch", "ok", "0.0s", "—"],
                    ["signals", "ok", "0.0s", "—"],
                    ["execute", "ok", "0.0s", "—"],
                    ["analytics", "ok", "0.0s", "—"],
                ],
                empty_row_message="no phases ran",
            ),
        ],
        "notes": (
            "Empty state — no variants registered yet. This is expected for Week 1; "
            "Bollinger and MA-crossover (or Week-0-surfaced replacements) come online "
            "in Week 2 after the strategy-roster review."
        ),
        "generator": "replay.py v0.1.0",
    }


def test_v1_report_empty_state_is_fully_formed() -> None:
    out = render_v1_report(_empty_state_replay_data())

    assert "# algotrading-paper / replay" in out
    assert "Variant — null" in out
    assert "0 trades" in out
    assert "[run log →](runs/2026-05-02T160629.log)" in out

    assert "**—**" in out, "em-dash should mark not-yet-present slot"
    assert "**0**" in out, "zero is a real value, must render explicitly"
    assert "**$0.00**" in out, "zero P&L is real"
    assert "**100%**" in out

    assert "§ 01 — Per-variant performance" in out
    assert "no variants registered" in out

    assert "§ 02 — Bars in period · by symbol" in out
    assert "no bars yet" in out
    assert "§ 03 — Run summary" in out
    assert "§ 04 — Notes" in out

    assert "§ Flags · none" in out, "flags section collapsed when empty"

    assert out.rstrip().endswith(
        "[github.com/pwysocan-droid/algotrading-paper](https://github.com/pwysocan-droid/algotrading-paper)"
    )

    assert "no data yet" not in out
    assert "TODO" not in out


def test_v1_report_does_not_use_zero_where_value_is_unknown() -> None:
    """The em-dash convention is load-bearing.

    "Variants registered" is em-dash because the slot exists but no
    variants are *yet* registered. "Trades in period" is 0 because zero
    trades happened — that's a real measurement.
    """
    out = render_v1_report(_empty_state_replay_data())
    band_section = out.split("# algotrading-paper / replay")[1]
    band_section = band_section.split("§ 01")[0]
    variants_cell_idx = band_section.find("Variants registered")
    assert variants_cell_idx >= 0
    next_table_row = band_section.find("**", variants_cell_idx)
    assert "**—**" in band_section[next_table_row : next_table_row + 80]


def test_v1_report_with_flags_puts_them_above_table() -> None:
    data = _empty_state_replay_data()
    data["flags"] = ["Run failed at 2026-05-02T14:00 — Alpaca returned 503"]
    out = render_v1_report(data)
    flag_idx = out.find("🔴 § Flags · 1 active")
    table_idx = out.find("§ 01 — Per-variant performance")
    assert flag_idx >= 0
    assert table_idx > flag_idx, "flags above the dominant table when populated"


def test_v1_report_section_markers_use_section_sign() -> None:
    out = render_v1_report(_empty_state_replay_data())
    section_lines = [line for line in out.split("\n") if line.startswith("## ")]
    for line in section_lines:
        assert "§" in line, f"section header without § marker: {line!r}"


def test_v1_report_missing_required_key_raises() -> None:
    data = _empty_state_replay_data()
    del data["title"]
    with pytest.raises(ValueError, match="missing required key"):
        render_v1_report(data)


def test_render_index_empty_state_is_fully_formed() -> None:
    state = {
        "phase": "Phase 1",
        "week": 1,
        "timestamp": datetime(2026, 5, 2, 16, 6, 29, tzinfo=timezone.utc),
        "latest_links": [
            ("↗ latest replay", "reports/2026-05-02-replay.md"),
            ("↗ week-1 status", "week-1-status.md"),
        ],
        "stats": [
            Stat("System uptime", "100%", "last 4w"),
            Stat("Trades this week", "0", "paper"),
            Stat("Phase 2 gates", "0 / 3", "passed"),
            Stat("Days to phase 1 review", "56", "calendar"),
        ],
        "flags": [],
        "surfaces": [
            {
                "surface": "replay",
                "filename": "reports/2026-05-02-replay.md",
                "generated": datetime(2026, 5, 2, 16, 6, 29, tzinfo=timezone.utc),
                "status": "ok",
            },
            {"surface": "weekly A/B", "filename": None, "generated": None,
             "status": "not yet · Week 4"},
            {"surface": "recommendations", "filename": None, "generated": None,
             "status": "not yet · Week 4"},
            {"surface": "Friday adversarial review", "filename": None,
             "generated": None, "status": "first run · Week 1"},
        ],
        "reading_order": [
            ("replay", "the latest backtest snapshot."),
            ("status", "week-N-status.md is what you read on Monday."),
            ("recommendations", "candidate variants from the walk-forward tuner — Week 4 onward."),
            ("patterns", "monthly Claude pass over the decision log — Month 2 onward."),
            ("philosophy", "if you're lost, this is where you go."),
        ],
        "foundational_docs": [
            ("PROJECT.md", "PROJECT.md"),
            ("philosophy.md", "philosophy.md"),
            ("decision-log.md", "decision-log.md"),
            ("playbook.md", "playbook.md"),
            ("roadmap.md", "roadmap.md"),
            ("week-0-synthesis.md", "week-0-synthesis.md"),
            ("setup.md", "setup.md"),
        ],
    }
    out = render_index(state)
    assert "# algotrading-paper" in out
    assert "Phase 1" in out
    assert "Week 1" in out
    assert "**100%**" in out
    assert "**0**" in out
    assert "§ 01 — Surfaces" in out
    assert "§ 02 — Reading order" in out
    assert "§ 03 — Foundational documents" in out
    assert "§ Flags · none" in out
    assert "not yet · Week 4" in out
    assert "PROJECT.md" in out
    assert "no data yet" not in out


def test_render_index_idempotent() -> None:
    state = {
        "phase": "Phase 1",
        "week": 1,
        "timestamp": datetime(2026, 5, 2, 16, 6, 29, tzinfo=timezone.utc),
        "latest_links": [],
        "stats": [
            Stat("A", EMDASH, "—"),
            Stat("B", "0", "—"),
            Stat("C", "0", "—"),
            Stat("D", "0", "—"),
        ],
        "surfaces": [],
        "reading_order": [("a", "b")],
        "foundational_docs": [("PROJECT.md", "PROJECT.md")],
    }
    a = render_index(state)
    b = render_index(state)
    assert a == b
