"""The gauntlet — score the LLM-surfaced candidates over the 6-month window.

Each candidate runs alone through replay_variant (real fees + slippage)
and apply_portfolio_constraints (cooldown/exposure/concurrency), exactly
the pipeline that exposed the textbook strategies. Scored by the fitness
function Phase 1 discovered: edge per constraint slot = net P&L per
placed trade. Output: reports/gauntlet-YYYY-MM-DD.md with the ranking.

Registration of the top 2 is a separate, human-reviewed config change —
this script measures, it does not promote.

    python scripts/run_gauntlet.py [--days 180]
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import db
import replay
from config import SLIPPAGE_PCT, STRATEGY_VARIANTS, TAKER_FEE_PCT, WATCHED_SYMBOLS

CANDIDATES = [
    "liquidation_cascade_reclaim",
    "btc_leads_alt_lag_capture",
    "dead_zone_range_break",
    "volume_thrust_regime_shift",
    "weekend_illiquidity_momentum",
]


def run_gauntlet(days: int = 180, db_path: Path | None = None) -> list[dict]:
    end = datetime.now(timezone.utc)
    start = end - timedelta(days=days)
    window_days = float(days)

    results = []
    for name in CANDIDATES:
        variant = dict(STRATEGY_VARIANTS[name])
        variant["enabled"] = True  # local copy only — config stays disabled

        with db.connect(db_path) as conn:
            trades = replay.replay_variant(
                conn, name, variant, WATCHED_SYMBOLS, start, end,
                fee_pct=TAKER_FEE_PCT, slippage_pct=SLIPPAGE_PCT,
            )
        candidates_n = len(trades)
        trades = replay.apply_portfolio_constraints(trades)
        placed = [t for t in trades if t.accepted]
        pnls = [t.pnl_usd for t in placed if t.pnl_usd is not None]
        pcts = [t.pnl_pct for t in placed if t.pnl_pct is not None]
        total = sum(pnls)
        n = len(placed)
        wins = sum(1 for p in pnls if p > 0)
        sharpe = replay.sharpe_ratio(pcts, window_days)
        dd = replay.max_drawdown_pct(pnls)

        results.append({
            "name": name,
            "candidates": candidates_n,
            "placed": n,
            "total_pnl": total,
            "edge_per_slot": total / n if n else None,
            "win_rate": wins / n if n else None,
            "sharpe": sharpe,
            "max_dd": dd,
        })
        print(f"{name}: candidates={candidates_n} placed={n} "
              f"pnl=${total:,.2f} edge/slot="
              f"{'—' if n == 0 else f'${total / n:,.3f}'}")

    # rank: edge per slot, requiring a usable sample; zero-fire candidates sink
    results.sort(key=lambda r: (r["edge_per_slot"] is not None, r["edge_per_slot"] or 0), reverse=True)
    return results


def render_report(results: list[dict], days: int, now: datetime | None = None) -> str:
    ts = now or datetime.now(timezone.utc)
    em = "—"
    lines = [
        "# algotrading-paper / candidate gauntlet",
        "",
        f"{days}d constrained replay · fees {TAKER_FEE_PCT:.2%}/leg · "
        f"slippage {SLIPPAGE_PCT:.2%}/leg · ranked by edge per constraint slot",
        "",
        ts.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "",
        "| # | Candidate | candidates | placed | net P&L | edge/slot | win rate | Sharpe | max DD |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for i, r in enumerate(results, 1):
        lines.append(
            f"| {i} | `{r['name']}` | {r['candidates']:,} | {r['placed']:,} "
            f"| ${r['total_pnl']:,.2f} "
            f"| {em if r['edge_per_slot'] is None else f'${r['edge_per_slot']:,.3f}'} "
            f"| {em if r['win_rate'] is None else f'{r['win_rate']:.1%}'} "
            f"| {em if r['sharpe'] is None else f'{r['sharpe']:.2f}'} "
            f"| {em if r['max_dd'] is None else f'{r['max_dd']:.1f}%'} |"
        )
    lines += [
        "",
        "Notes: each candidate replayed alone under the full portfolio",
        "constraints; live behavior with a shared ceiling will differ. The",
        "gauntlet measures; registration of the top 2 is a reviewed config",
        "change plus a decision-log entry. n < 30 placed means any claim",
        "is statistically unreliable regardless of sign (small-sample trap).",
        "",
        "---",
        "",
        "generated by scripts/run_gauntlet.py",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the candidate gauntlet")
    parser.add_argument("--days", type=int, default=180)
    args = parser.parse_args()

    db.migrate()
    results = run_gauntlet(days=args.days)
    report = render_report(results, args.days)
    out = Path(__file__).resolve().parent.parent / "reports" / (
        f"gauntlet-{datetime.now(timezone.utc).date().isoformat()}.md"
    )
    out.write_text(report)
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
